### ISSUE TITLE
Crash when `title-intro-en` is empty

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-standoc#22]
When `:title-intro-en:` is set to empty in the document header, it crashes:

```
bundler: failed to load command: metanorma (/Users/myself/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/bin/metanorma)
NoMethodError: undefined method `source' for nil:NilClass
  /Users/myself/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/metanorma-standoc-1.0.9/lib/asciidoctor/standoc/front.rb:150:in `asciidoc_sub'
  /Users/myself/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/metanorma-iso-1.0.9/lib/asciidoctor/iso/front.rb:116:in `block in title_intro'
```

**Comment by ronaldtse** [comment]
This is from a header like this:

```
:title-intro-en:
:title-main-en: Guidelines for Implementation of the Common Patent Policy for ITU-T/ITU-R/ISO/IEC
```

**Comment by opoudjis** [comment]
Crash is in the method which applies Asciidoctor substitutions to a string (by building a new Asciidoctor document using the string -- the substitutions happen by default). The method returns nil if it is passed nil; it now also returns "" if it is passed "", rather than trying to create an empty document.
